# Numpy 

In [2]:
import numpy as np

In [3]:
randomArray = np.random.randn(10)*100

In [4]:
randomArray

array([-271.56517993,    2.38981329,   13.61954942,   20.28758983,
       -230.92477553,  -41.14076126, -164.00907641,   46.6208042 ,
        -18.40219049,  -38.71700861])

In [5]:
randomArray.ndim

1

In [6]:
randomArray.shape

(10,)

In [10]:
twoD = np.array([[1,2,3],[4,5,6],[7,8,9],[2,3,4]])

In [11]:
twoD

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [2, 3, 4]])

In [12]:
twoD.shape

(4, 3)

In [13]:
zerroD = np.array(100)

In [14]:
zerroD.ndim

0

In [15]:
zerroD.shape

()

In [18]:
miscD = np.array([[[99]]])
print(miscD)
print(miscD.ndim)
print(miscD.shape)

[[[99]]]
3
(1, 1, 1)


In [24]:
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [25]:
flat = np.ravel(a)

In [26]:
flat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
flat = flat.reshape(12)

In [29]:
z = np.array([22,33,44,55,66,77])

In [30]:
z

array([22, 33, 44, 55, 66, 77])

In [32]:
rz = z.reshape(2,3)

In [33]:
rz

array([[22, 33, 44],
       [55, 66, 77]])

In [35]:
rz = np.ravel(rz)

In [36]:
rz

array([22, 33, 44, 55, 66, 77])

In [44]:
TwoD = np.arange(36).reshape(6,6)

In [45]:
TwoD

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [47]:
threeD = TwoD.reshape(3,3,4)

In [48]:
threeD

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [49]:
rebacktwoD = threeD.reshape(6,6)

In [50]:
rebacktwoD

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [52]:
threeD = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[3,6,8],[8,7,6],[9,8,7]]])

In [53]:
threeD

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[3, 6, 8],
        [8, 7, 6],
        [9, 8, 7]]])

In [57]:
threeD= np.array([[[1,2],[2,4],[3,4]],[[5,6],[7,8],[9,0]],[[0,1],[2,0],[3,0]]])

In [58]:
threeD

array([[[1, 2],
        [2, 4],
        [3, 4]],

       [[5, 6],
        [7, 8],
        [9, 0]],

       [[0, 1],
        [2, 0],
        [3, 0]]])

In [61]:
TwoD / TwoD  

C:\Users\DELL\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[nan,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.]])

In [62]:
TwoD * TwoD 

array([[   0,    1,    4,    9,   16,   25],
       [  36,   49,   64,   81,  100,  121],
       [ 144,  169,  196,  225,  256,  289],
       [ 324,  361,  400,  441,  484,  529],
       [ 576,  625,  676,  729,  784,  841],
       [ 900,  961, 1024, 1089, 1156, 1225]])

In [63]:
n1 = np.arange(12).reshape(4,3)

In [64]:
n2 = np.random.randn(12).reshape(4,3)

In [65]:
n1 + n2

array([[-1.910839  ,  2.32959714,  2.22025195],
       [ 3.98659767,  5.54014952,  3.85579177],
       [ 5.71708671,  7.53688852,  9.18996156],
       [ 9.28217542, 10.73867756,  9.4416508 ]])

In [66]:
#columne to row multiplictaion 

In [67]:
n3 = np.arange(18).reshape(3,6)

In [68]:
n3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [69]:
n1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [70]:
n1 * n3

ValueError: operands could not be broadcast together with shapes (4,3) (3,6) 

In [71]:
#shape is change so use @ for multiply
n1@n3

array([[ 30,  33,  36,  39,  42,  45],
       [ 84,  96, 108, 120, 132, 144],
       [138, 159, 180, 201, 222, 243],
       [192, 222, 252, 282, 312, 342]])

In [73]:
#second option for multiply
np.dot(n1,n3)

array([[ 30,  33,  36,  39,  42,  45],
       [ 84,  96, 108, 120, 132, 144],
       [138, 159, 180, 201, 222, 243],
       [192, 222, 252, 282, 312, 342]])

In [74]:
#third option for multiply
n1.dot(n3)

array([[ 30,  33,  36,  39,  42,  45],
       [ 84,  96, 108, 120, 132, 144],
       [138, 159, 180, 201, 222, 243],
       [192, 222, 252, 282, 312, 342]])

In [80]:
zerooos = np.zeros(4,dtype = "int8")

In [81]:
zerooos

array([0, 0, 0, 0], dtype=int8)

In [82]:
zeroos = np.zeros((4,5),dtype = "int8")

In [83]:
zeroos

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int8)

In [84]:
oness = np.ones((5,5),dtype = "int8")

In [86]:
oness * 50

array([[50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50]], dtype=int8)

In [87]:
full = np.full((4,4),100)

In [90]:
full

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [91]:
empty = np.empty((4,4,4))

In [92]:
empty

array([[[4.45e-323, 0.00e+000, 1.35e-321, 0.00e+000],
        [0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000],
        [0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000],
        [0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000]],

       [[0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000],
        [0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000],
        [0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000],
        [0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000]],

       [[0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000],
        [0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000],
        [0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000],
        [0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000]],

       [[0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000],
        [0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000],
        [0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000],
        [0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000]]])

In [97]:
n3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [99]:
like = np.zeros_like(n3)

In [100]:
like

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [110]:
i = np.eye(5,5)

# astype 

In [108]:
j = i.astype("int") # change data type

In [109]:
j

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

# Basic Indexing and slicing

In [111]:
alist = [99,77,66,33,22]

In [114]:
type(alist[0:3])

list

In [119]:
tDarray = np.arange(36).reshape(6,6)
tDarray

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [120]:
tDarray[3,2]

20

In [121]:
tDarray[3][2]

20

In [122]:
#tDarray[row,column]
#tDarray[start:end, start:end]
tDarray[2:5,1:4]

array([[13, 14, 15],
       [19, 20, 21],
       [25, 26, 27]])

In [123]:
tDarray[5:,3:4]

array([[33]])

In [125]:
tDarray[1:2,2:5]

array([[ 8,  9, 10]])