# Numpy vs python

In [1]:
import numpy as np

In [2]:
l = range(10000)

In [3]:
d = np.arange(10000)

In [7]:
%time for i in range(1,10): r=[x*2 for x in l]

Wall time: 12 ms


In [8]:
%time for i in range(1,10): r = d*2 

Wall time: 1 ms


# ndarray

In [9]:
x = np.zeros((4,4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.empty((6,6))

array([[ 3.13400801e-312,  3.13368660e-312,  1.37186216e+142,
         6.67268208e-313,  9.09846607e-307,  1.33360300e+241],
       [ 1.32794497e-310,  3.54249089e+262,  5.39948460e-313,
         3.67767335e-308,  1.33360353e+241,  1.54523733e-310],
       [-1.53446210e-253,  7.52148039e-313,  4.85213860e-308,
         1.33360365e+241,  3.33789938e-310,  1.02318154e-012],
       [ 1.32508690e-312,  2.88067937e+214,  3.22931900e+185,
         4.02977901e-270,  7.45409668e-251,  7.88373233e-251],
       [ 1.73156923e-260,  4.50669309e-270,  1.61294708e-231,
         9.93855585e-270,  6.37487135e-288,  1.61285740e-231],
       [ 7.43023336e-251,  1.13750527e-268,  2.84531714e-269,
         3.03808733e-268,  1.97626258e-323,  6.80923702e-307]])

In [14]:
l = [1,4,6,7]

In [15]:
np.array(l)

array([1, 4, 6, 7])

In [21]:
np.arange(1,100,10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [30]:
x = np.arange(1,100,10)

In [31]:
x.shape

(10,)

In [38]:
x= np.zeros((10,10))
x.shape

(10, 10)

In [41]:
y=x.reshape((2,2,5,5))    #reshape
y

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [43]:
y.dtype   #check data type

dtype('float64')

In [45]:
y.ndim   #check dimension

4

# Vectorized operations 

In [47]:
a=np.random.randn((10))

In [48]:
b=np.random.randn((10))

In [49]:
a

array([-0.67180205, -0.71120135, -1.07799507, -0.1945003 , -1.59240435,
       -0.36370021,  1.8059501 ,  0.27886374,  1.02474367, -0.17510417])

In [50]:
b

array([-6.90719764e-01, -1.65222876e+00,  1.00549787e+00,  8.41401750e-01,
        1.00359172e+00, -1.59397647e+00, -2.05204826e-01,  4.10588277e-04,
        2.04233636e+00,  8.19978997e-01])

In [51]:
a + b

array([-1.36252182, -2.36343011, -0.0724972 ,  0.64690145, -0.58881264,
       -1.95767668,  1.60074528,  0.27927433,  3.06708003,  0.64487483])

In [52]:
a - b

array([ 0.01891771,  0.94102741, -2.08349294, -1.03590204, -2.59599607,
        1.23027626,  2.01115493,  0.27845315, -1.0175927 , -0.99508316])

In [53]:
2 * a

array([-1.34360411, -1.4224027 , -2.15599014, -0.38900059, -3.18480871,
       -0.72740042,  3.6119002 ,  0.55772747,  2.04948733, -0.35020833])

In [54]:
1 / a

array([-1.4885337 , -1.40607158, -0.92764803, -5.14138037, -0.6279812 ,
       -2.74951726,  0.55372515,  3.58598078,  0.9758538 , -5.71088642])

In [55]:
a > 0

array([False, False, False, False, False, False,  True,  True,  True,
       False])

In [56]:
a[a>0]    #select true elements 

array([1.8059501 , 0.27886374, 1.02474367])

# Indexing and Slicing

In [57]:
x = np.array([1,4,9,5,3])    

In [58]:
x[4]

3

In [60]:
x[x>3]       #boolean indexing

array([4, 9, 5])

In [61]:
x[[2,1]]     #fency indexing 

array([9, 4])

In [62]:
x = np.random.randn(10,10)    #slicing

In [63]:
x

array([[-0.40181496,  0.48904992,  0.70942451,  0.51170546,  1.31080593,
        -0.37777095, -0.23531785,  1.33759292,  1.03165076,  3.89815223],
       [-1.21347073, -1.66675923,  1.8525403 , -0.1529813 ,  1.14211003,
        -0.82764681, -0.25699659, -0.77153688, -1.27321283,  1.02583885],
       [ 0.23881445, -1.76125044,  0.50626768, -0.630212  , -1.00746847,
        -0.36120756, -1.45420812, -1.80528268,  1.60184275, -0.09700793],
       [-1.06135875,  1.00304219,  0.4360044 ,  0.65614329,  0.17013243,
         0.76653723, -0.45666427,  0.1512989 , -0.09981012, -1.84229921],
       [ 0.17446456,  1.12278295,  0.55459609,  0.29853756,  0.52988846,
         2.30062875, -3.17262753,  0.07132686,  0.38583192,  0.42203945],
       [-0.35201689,  1.81374355, -0.31915988,  0.56845995,  0.61956695,
         2.40375413,  0.91949783, -0.36036712,  2.40273355,  0.93307255],
       [ 1.22433809, -0.60665811, -0.40672011, -0.67063641,  0.39132896,
         0.40550347, -0.43998075,  0.2561916 

In [64]:
x[0]

array([-0.40181496,  0.48904992,  0.70942451,  0.51170546,  1.31080593,
       -0.37777095, -0.23531785,  1.33759292,  1.03165076,  3.89815223])

In [65]:
x[0][4]

1.3108059315131286

In [67]:
x[1:10:2]

array([[-1.21347073, -1.66675923,  1.8525403 , -0.1529813 ,  1.14211003,
        -0.82764681, -0.25699659, -0.77153688, -1.27321283,  1.02583885],
       [-1.06135875,  1.00304219,  0.4360044 ,  0.65614329,  0.17013243,
         0.76653723, -0.45666427,  0.1512989 , -0.09981012, -1.84229921],
       [-0.35201689,  1.81374355, -0.31915988,  0.56845995,  0.61956695,
         2.40375413,  0.91949783, -0.36036712,  2.40273355,  0.93307255],
       [ 0.63191139,  0.28765352,  0.24203058,  0.6430512 ,  1.4773375 ,
        -3.09967108,  0.57105742,  0.1529114 , -0.34453673, -0.02067584],
       [-1.32079523, -0.82957375,  0.53334251,  0.4078748 ,  0.42009529,
         1.30930506,  1.51259489, -0.25146543, -1.66249684,  0.90783621]])

In [68]:
x[::,0:4]

array([[-0.40181496,  0.48904992,  0.70942451,  0.51170546],
       [-1.21347073, -1.66675923,  1.8525403 , -0.1529813 ],
       [ 0.23881445, -1.76125044,  0.50626768, -0.630212  ],
       [-1.06135875,  1.00304219,  0.4360044 ,  0.65614329],
       [ 0.17446456,  1.12278295,  0.55459609,  0.29853756],
       [-0.35201689,  1.81374355, -0.31915988,  0.56845995],
       [ 1.22433809, -0.60665811, -0.40672011, -0.67063641],
       [ 0.63191139,  0.28765352,  0.24203058,  0.6430512 ],
       [ 1.09792781,  0.00967359, -0.60623908, -1.10692917],
       [-1.32079523, -0.82957375,  0.53334251,  0.4078748 ]])

In [71]:
x = np.ones((5,5))
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [74]:
x[1:-1,1:-1]=0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# Functions

In [80]:
x = np.array([10,9,8,6,11])
x

array([10,  9,  8,  6, 11])

In [79]:
np.sqrt(x)

array([3.16227766, 3.        , 2.82842712, 2.44948974, 3.31662479])

In [81]:
np.power(x,2)

array([100,  81,  64,  36, 121], dtype=int32)

In [82]:
y = [7,1,2,3,-1]

In [84]:
np.maximum(x,y) 

array([10,  9,  8,  6, 11])

# Where

In [86]:
salary = np.array([0,1,1000,5000])
salary

array([   0,    1, 1000, 5000])

In [94]:
np.where(salary <=0 , 25000,salary)

array([ 25000,      1, 100000, 500000])

In [95]:
np.where(salary <=0, 'NOT Ok', 'OK')

array(['NOT Ok', 'OK', 'OK', 'OK'], dtype='<U6')

# Statistical

In [96]:
x = np.array([1,2,3,4,5])

In [97]:
x.mean()

3.0

In [98]:
x.cumsum()

array([ 1,  3,  6, 10, 15], dtype=int32)

In [99]:
x.cumprod()

array([  1,   2,   6,  24, 120], dtype=int32)

In [104]:
y = x > 6
y

array([False, False, False, False, False])

In [105]:
y.sum()

0

In [106]:
y.any()

False

In [107]:
y.all()

False

In [111]:
y = x>3
y

array([False, False, False,  True,  True])

In [112]:
y.sum()

2

In [113]:
y.all()

False

In [114]:
x.sort()

In [115]:
x

array([1, 2, 3, 4, 5])

In [118]:
np.unique(x)

array([1, 2, 3, 4, 5])

# Filing

In [3]:
import numpy as np

In [4]:
x = [1,4,6,9]
y = [8,6,5]

In [5]:
np.save('testx',x)

In [6]:
loadx = np.load('testx.npy')

In [7]:
loadx

array([1, 4, 6, 9])

In [12]:
np.savez('testxy',x,y)

In [14]:
loadxy = np.load('testxy.npz')

In [15]:
loadxy

# linear algebra

In [18]:
x = np.random.randn(3,2)

In [19]:
y = np.random.randn(2,3)

In [20]:
x.dot(y)

array([[ 1.46348558, -0.05131265, -0.39330711],
       [ 2.44013294, -0.16657559, -0.12123132],
       [-4.8997203 ,  0.21429103,  1.03639851]])

In [21]:
x.transpose()

array([[ 0.64641828,  0.99242856, -2.11941489],
       [-0.19097003, -1.34165687,  1.17608615]])

In [22]:
x.trace()

-0.6952385872841449

# Random

In [23]:
np.random.seed(7)

In [24]:
np.random.normal(size=(3,3))

array([[ 1.69052570e+00, -4.65937371e-01,  3.28201637e-02],
       [ 4.07516283e-01, -7.88923029e-01,  2.06557291e-03],
       [-8.90385858e-04, -1.75472431e+00,  1.01765801e+00]])

In [25]:
np.random.uniform(size=(3,4))

array([[0.38094113, 0.06593635, 0.2881456 , 0.90959353],
       [0.21338535, 0.45212396, 0.93120602, 0.02489923],
       [0.60054892, 0.9501295 , 0.23030288, 0.54848992]])

# Reshape

In [28]:
x=np.random.randn(4,5)
x

array([[ 1.19308592, -0.36881847, -1.90636988, -0.09961063,  1.6995373 ],
       [-0.38342312, -0.88985686, -1.19359192, -1.05001681, -0.30019374],
       [-1.17998209,  1.49763912, -0.28263524,  0.10864837,  1.43823952],
       [ 1.50331852, -0.21273297,  0.33197422,  0.73502658, -0.19285546]])

In [30]:
x.reshape((2,2,5))

array([[[ 1.19308592, -0.36881847, -1.90636988, -0.09961063,
          1.6995373 ],
        [-0.38342312, -0.88985686, -1.19359192, -1.05001681,
         -0.30019374]],

       [[-1.17998209,  1.49763912, -0.28263524,  0.10864837,
          1.43823952],
        [ 1.50331852, -0.21273297,  0.33197422,  0.73502658,
         -0.19285546]]])

In [31]:
x.reshape((2,2,5),order='F')

array([[[ 1.19308592, -0.36881847, -1.90636988, -0.09961063,
          1.6995373 ],
        [-1.17998209,  1.49763912, -0.28263524,  0.10864837,
          1.43823952]],

       [[-0.38342312, -0.88985686, -1.19359192, -1.05001681,
         -0.30019374],
        [ 1.50331852, -0.21273297,  0.33197422,  0.73502658,
         -0.19285546]]])

In [32]:
x.reshape((2,2,-1))

array([[[ 1.19308592, -0.36881847, -1.90636988, -0.09961063,
          1.6995373 ],
        [-0.38342312, -0.88985686, -1.19359192, -1.05001681,
         -0.30019374]],

       [[-1.17998209,  1.49763912, -0.28263524,  0.10864837,
          1.43823952],
        [ 1.50331852, -0.21273297,  0.33197422,  0.73502658,
         -0.19285546]]])

In [33]:
x

array([[ 1.19308592, -0.36881847, -1.90636988, -0.09961063,  1.6995373 ],
       [-0.38342312, -0.88985686, -1.19359192, -1.05001681, -0.30019374],
       [-1.17998209,  1.49763912, -0.28263524,  0.10864837,  1.43823952],
       [ 1.50331852, -0.21273297,  0.33197422,  0.73502658, -0.19285546]])

In [34]:
x.ravel()

array([ 1.19308592, -0.36881847, -1.90636988, -0.09961063,  1.6995373 ,
       -0.38342312, -0.88985686, -1.19359192, -1.05001681, -0.30019374,
       -1.17998209,  1.49763912, -0.28263524,  0.10864837,  1.43823952,
        1.50331852, -0.21273297,  0.33197422,  0.73502658, -0.19285546])

In [35]:
x.flatten()

array([ 1.19308592, -0.36881847, -1.90636988, -0.09961063,  1.6995373 ,
       -0.38342312, -0.88985686, -1.19359192, -1.05001681, -0.30019374,
       -1.17998209,  1.49763912, -0.28263524,  0.10864837,  1.43823952,
        1.50331852, -0.21273297,  0.33197422,  0.73502658, -0.19285546])

# Concatenate

In [36]:
x=[[1,3,5],[7,9,0]]

In [41]:
arr1 = np.array(x)

In [42]:
y = [[2,4,6],[3,5,8]]

In [43]:
arr2 = np.array(y)

In [44]:
np.concatenate((arr1,arr2),axis=0)

array([[1, 3, 5],
       [7, 9, 0],
       [2, 4, 6],
       [3, 5, 8]])

In [45]:
np.concatenate((arr1,arr2),axis=1)

array([[1, 3, 5, 2, 4, 6],
       [7, 9, 0, 3, 5, 8]])

In [46]:
np.vstack((arr1,arr2))

array([[1, 3, 5],
       [7, 9, 0],
       [2, 4, 6],
       [3, 5, 8]])

In [47]:
np.hstack((arr1,arr2))

array([[1, 3, 5, 2, 4, 6],
       [7, 9, 0, 3, 5, 8]])

# Split

In [51]:
import numpy as np

In [52]:
x=[1,3,5,7,9,3,4]

In [53]:
d= np.array(x)

In [56]:
np.split(d,[2,5])

[array([1, 3]), array([5, 7, 9]), array([3, 4])]

In [57]:
x=[[1,3,5,7,9,3,4],[11,13,15,17,19,13,41]]

In [58]:
d = np.array(x)

In [60]:
np.split(d,[4,6],axis=1)

[array([[ 1,  3,  5,  7],
        [11, 13, 15, 17]]), array([[ 9,  3],
        [19, 13]]), array([[ 4],
        [41]])]

In [61]:
np.split(d,[1],axis=0)

[array([[1, 3, 5, 7, 9, 3, 4]]), array([[11, 13, 15, 17, 19, 13, 41]])]

# Repeat_tile

In [62]:
d = np.array([1,5,7,9])

In [63]:
np.repeat(d,3)

array([1, 1, 1, 5, 5, 5, 7, 7, 7, 9, 9, 9])

In [64]:
np.tile(d,2)

array([1, 5, 7, 9, 1, 5, 7, 9])