# Pandas Series 

In [1]:
import pandas as pd

In [2]:
obj = pd.Series([4,7,-5,3])
print(obj)

0    4
1    7
2   -5
3    3
dtype: int64


In [10]:
print(obj.values)
print(obj.index)

[ 4  7 -5  3]
RangeIndex(start=0, stop=4, step=1)


In [11]:
sales = pd.Series([100,200,100,400])

In [12]:
print(sales.values)

[100 200 100 400]


In [13]:
print(sales.index)

RangeIndex(start=0, stop=4, step=1)


In [14]:
sales = pd.Series([100,200,100,400], index = (['a','b','c','d']))

In [15]:
sales

a    100
b    200
c    100
d    400
dtype: int64

In [17]:
print(sales.values)

[100 200 100 400]


In [18]:
print(sales.index)

Index(['a', 'b', 'c', 'd'], dtype='object')


In [23]:
sales = pd.Series([100,200,100,400], index = ['a','b','c','d'], name= '4 sales')

In [24]:
sales

a    100
b    200
c    100
d    400
Name: 4 sales, dtype: int64

In [26]:
data = pd.Series([20,30,35,40,45,50,0],
                 index = ('mon','tues','wed','thur','fri','sat','sun'))
data

mon     20
tues    30
wed     35
thur    40
fri     45
sat     50
sun      0
dtype: int64

In [29]:
print(data[1])

30


In [34]:
print(data['fri'])

45


In [36]:
print(data[[3,5]])

thur    40
sat     50
dtype: int64


In [37]:
print(data[['fri','mon']])

fri    45
mon    20
dtype: int64


In [41]:
print(data[data>30])

wed     35
thur    40
fri     45
sat     50
dtype: int64


In [42]:
data * 2

mon      40
tues     60
wed      70
thur     80
fri      90
sat     100
sun       0
dtype: int64

In [44]:
data = data*2
data

mon      80
tues    120
wed     140
thur    160
fri     180
sat     200
sun       0
dtype: int64

In [46]:
data = data/2

In [48]:
data     # float ans due to divide 

mon      40.0
tues     60.0
wed      70.0
thur     80.0
fri      90.0
sat     100.0
sun       0.0
dtype: float64

In [49]:
'mon' in data     #any index exist in data 

True

In [50]:
'sund' in data

False

In [51]:
import numpy as np

In [53]:
ar = np.array([3,2,5,6,7])
ind = np.array(['a','b','c','d','e'])
obj2 = pd.Series(ar ,index=ind)

In [54]:
obj2

a    3
b    2
c    5
d    6
e    7
dtype: int32

In [66]:
state = {'sindh': 3500 , 'punjab': 4500 , 'kpk': 5000 , 'baloc': 5500 }
tax = pd.Series(state)

In [61]:
tax

sindh     3500
punjab    4500
kpk       5000
baloc     5500
dtype: int64

In [62]:
tax.index

Index(['sindh', 'punjab', 'kpk', 'baloc'], dtype='object')

In [63]:
tax.values

array([3500, 4500, 5000, 5500], dtype=int64)

In [67]:
pd.isnull(data)

mon     False
tues    False
wed     False
thur    False
fri     False
sat     False
sun     False
dtype: bool

In [68]:
data.isnull()

mon     False
tues    False
wed     False
thur    False
fri     False
sat     False
sun     False
dtype: bool

In [70]:
data.name = 'state tax paying capicity'
data.index.name = 'state name'
print(data)
print(data.index)

state name
mon      40.0
tues     60.0
wed      70.0
thur     80.0
fri      90.0
sat     100.0
sun       0.0
Name: state tax paying capicity, dtype: float64
Index(['mon', 'tues', 'wed', 'thur', 'fri', 'sat', 'sun'], dtype='object', name='state name')
